### ISSUE TITLE
py2app doesn't work with python 3.8

### ISSUE THREAD

**Issue by ronaldoussoren** [ronaldoussoren/py2app#269]
**[Original report](https://bitbucket.org/ronaldoussoren/py2app/issue/269) by Ronald Oussoren (Bitbucket: [ronaldoussoren](https://bitbucket.org/ronaldoussoren), GitHub: [ronaldoussoren](https://github.com/ronaldoussoren)).**

----------------------------------------

As the title says, with 3.8b3. Both normal and alias builds.

**Comment by ronaldoussoren** [comment]
This is fixed in py2app 0.20.

**Comment by itaymish** [comment]
For me, py2app still doesn't support Python 3.8, and I'm using py2app 0.23.

**Comment by ronaldoussoren** [comment]
In what way does it not work? 

How did you install Python (python.org installer, home-brew, anaconda, ...)?

**Comment by itaymish** [comment]
I installed Python from python.org.

**Comment by ronaldoussoren** [comment]
And what doesn't work?  I cannot fix problems if I don't know what's not working.

**Comment by itaymish** [comment]
I made a Tkinter app, and I used some features that only available in Python 3. I build the app and when I tried to run it it shows me the app, but without that features that I used.

**Comment by FPFdeveloper** [comment]
Hi, I used py2app 0.27 with python 3.8.5 on an Intel based Monterey 12.1. 
The app appears all black but the Tkinter GUI behind it works (when I click where a button is supposed to be it works, the GUI is simply covered by a black screen). 
There are n errors on the console and it works fine on VScode.
Do you recognise this issue? Kindly let me know.

**Comment by ronaldoussoren** [comment]
@FPFdeveloper : Very odd. I cannot reproduce this in a VM running Monterey 12.3, Python 3.8.8 and pyobjc 0.28 (upcoming release). Python was installed using the installer on python.org that does not have support for arm64 (Apple Silicon).
